---
# author: jimmyx


- name: check | 服务家目录如果不存在则创建。
  file: path={{ deploy_service_workpath }} owner={{ deploy_service_user }} group={{ deploy_service_user }} state=directory
  
- name: check | 代码存储目录如果不存在则创建。
  file: path={{ item }} state=directory owner={{ deploy_service_user }} group={{ deploy_service_user }}
  with_items:
   - "{{ deploy_code_online_path }}"
   - "{{ deploy_code_previous_path }}"
   - "{{ deploy_code_history_path }}"
    #owner: "{{ deploy_service_user }}"
    #group: "{{ deploy_service_user }}"

- name : check | 清空代码更新的目录。
  file: "path={{ deploy_code_online_path }}/ state=absent"

   
